/*
This script is just helper for generating purposes
Use this code to catch the keys

 const keys = new Map();

 currentLayout = 'en'

document.addEventListener("keydown", function (event) {
  let { key, code, altKey, shiftKey, keyCode } = event;
  let keyObj = {
    key: key,
    code: code,
    altKey: altKey,
    shiftKey: shiftKey,
    keyCode: keyCode,
  };

  if(keys.has(keyCode)){
      if(keyObj.shiftKey){
        let obj = keys.get(keyCode);
        obj.keyS = keyObj.key;
      }
      if (currentLayout === 'ru'){
        let obj = keys.get(keyCode);
        obj.keyRu = keyObj.key;
        if(keyObj.shiftKey){
            let obj = keys.get(keyCode);
            obj.keyRuS = keyObj.key;
          }
      }
  }else {
      keys.set(keyCode, keyObj);
  }

  console.log(keyObj);
});

*/
const keysSet = [
  {
    key: '§',
    code: 'Backquote',
    altKey: false,
    shiftKey: false,
    keyCode: 192,
  },
  {
    key: '1',
    code: 'Digit1',
    altKey: false,
    shiftKey: false,
    keyCode: 49,
  },
  {
    key: '2',
    code: 'Digit2',
    altKey: false,
    shiftKey: false,
    keyCode: 50,
  },
  {
    key: '3',
    code: 'Digit3',
    altKey: false,
    shiftKey: false,
    keyCode: 51,
  },
  {
    key: '4',
    code: 'Digit4',
    altKey: false,
    shiftKey: false,
    keyCode: 52,
  },
  {
    key: '5',
    code: 'Digit5',
    altKey: false,
    shiftKey: false,
    keyCode: 53,
  },
  {
    key: '6',
    code: 'Digit6',
    altKey: false,
    shiftKey: false,
    keyCode: 54,
  },
  {
    key: '7',
    code: 'Digit7',
    altKey: false,
    shiftKey: false,
    keyCode: 55,
  },
  {
    key: '8',
    code: 'Digit8',
    altKey: false,
    shiftKey: false,
    keyCode: 56,
  },
  {
    key: '9',
    code: 'Digit9',
    altKey: false,
    shiftKey: false,
    keyCode: 57,
  },
  {
    key: '0',
    code: 'Digit0',
    altKey: false,
    shiftKey: false,
    keyCode: 48,
  },
  {
    key: '-',
    code: 'Minus',
    altKey: false,
    shiftKey: false,
    keyCode: 189,
  },
  {
    key: '=',
    code: 'Equal',
    altKey: false,
    shiftKey: false,
    keyCode: 187,
  },
  {
    key: 'Backspace',
    code: 'Backspace',
    altKey: false,
    shiftKey: false,
    keyCode: 8,
  },
  {
    key: 'Tab',
    code: 'Tab',
    altKey: false,
    shiftKey: false,
    keyCode: 9,
  },
  {
    key: 'q',
    code: 'KeyQ',
    altKey: false,
    shiftKey: false,
    keyCode: 81,
  },
  {
    key: 'w',
    code: 'KeyW',
    altKey: false,
    shiftKey: false,
    keyCode: 87,
  },
  {
    key: 'e',
    code: 'KeyE',
    altKey: false,
    shiftKey: false,
    keyCode: 69,
  },
  {
    key: 'r',
    code: 'KeyR',
    altKey: false,
    shiftKey: false,
    keyCode: 82,
  },
  {
    key: 't',
    code: 'KeyT',
    altKey: false,
    shiftKey: false,
    keyCode: 84,
  },
  {
    key: 'y',
    code: 'KeyY',
    altKey: false,
    shiftKey: false,
    keyCode: 89,
  },
  {
    key: 'u',
    code: 'KeyU',
    altKey: false,
    shiftKey: false,
    keyCode: 85,
  },
  {
    key: 'i',
    code: 'KeyI',
    altKey: false,
    shiftKey: false,
    keyCode: 73,
  },
  {
    key: 'o',
    code: 'KeyO',
    altKey: false,
    shiftKey: false,
    keyCode: 79,
  },
  {
    key: 'p',
    code: 'KeyP',
    altKey: false,
    shiftKey: false,
    keyCode: 80,
  },
  {
    key: '[',
    code: 'BracketLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 219,
  },
  {
    key: ']',
    code: 'BracketRight',
    altKey: false,
    shiftKey: false,
    keyCode: 221,
  },
  {
    key: 'Enter',
    code: 'Enter',
    altKey: false,
    shiftKey: false,
    keyCode: 13,
  },
  {
    key: 'CapsLock',
    code: 'CapsLock',
    altKey: false,
    shiftKey: false,
    keyCode: 20,
  },
  {
    key: 'a',
    code: 'KeyA',
    altKey: false,
    shiftKey: false,
    keyCode: 65,
  },
  {
    key: 's',
    code: 'KeyS',
    altKey: false,
    shiftKey: false,
    keyCode: 83,
  },
  {
    key: 'd',
    code: 'KeyD',
    altKey: false,
    shiftKey: false,
    keyCode: 68,
  },
  {
    key: 'f',
    code: 'KeyF',
    altKey: false,
    shiftKey: false,
    keyCode: 70,
  },
  {
    key: 'g',
    code: 'KeyG',
    altKey: false,
    shiftKey: false,
    keyCode: 71,
  },
  {
    key: 'h',
    code: 'KeyH',
    altKey: false,
    shiftKey: false,
    keyCode: 72,
  },
  {
    key: 'j',
    code: 'KeyJ',
    altKey: false,
    shiftKey: false,
    keyCode: 74,
  },
  {
    key: 'k',
    code: 'KeyK',
    altKey: false,
    shiftKey: false,
    keyCode: 75,
  },
  {
    key: 'l',
    code: 'KeyL',
    altKey: false,
    shiftKey: false,
    keyCode: 76,
  },
  {
    key: ';',
    code: 'Semicolon',
    altKey: false,
    shiftKey: false,
    keyCode: 186,
  },
  {
    key: "'",
    code: 'Quote',
    altKey: false,
    shiftKey: false,
    keyCode: 222,
  },
  {
    key: '\\',
    code: 'Backslash',
    altKey: false,
    shiftKey: false,
    keyCode: 220,
  },
  {
    key: 'Shift',
    code: 'ShiftLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 16,
  },
  {
    key: '`',
    code: 'IntlBackslash',
    altKey: false,
    shiftKey: false,
    keyCode: 192,
  },
  {
    key: 'z',
    code: 'KeyZ',
    altKey: false,
    shiftKey: false,
    keyCode: 90,
  },
  {
    key: 'x',
    code: 'KeyX',
    altKey: false,
    shiftKey: false,
    keyCode: 88,
  },
  {
    key: 'c',
    code: 'KeyC',
    altKey: false,
    shiftKey: false,
    keyCode: 67,
  },
  {
    key: 'v',
    code: 'KeyV',
    altKey: false,
    shiftKey: false,
    keyCode: 86,
  },
  {
    key: 'b',
    code: 'KeyB',
    altKey: false,
    shiftKey: false,
    keyCode: 66,
  },
  {
    key: 'n',
    code: 'KeyN',
    altKey: false,
    shiftKey: false,
    keyCode: 78,
  },
  {
    key: 'm',
    code: 'KeyM',
    altKey: false,
    shiftKey: false,
    keyCode: 77,
  },
  {
    key: ',',
    code: 'Comma',
    altKey: false,
    shiftKey: false,
    keyCode: 188,
  },
  {
    key: '.',
    code: 'Period',
    altKey: false,
    shiftKey: false,
    keyCode: 190,
  },
  {
    key: '↑',
    code: 'ArrowUp',
    altKey: false,
    shiftKey: false,
    keyCode: 38,
  },
  {
    key: '/',
    code: 'Slash',
    altKey: false,
    shiftKey: false,
    keyCode: 191,
  },
  {
    key: 'Shift',
    code: 'ShiftRight',
    altKey: false,
    shiftKey: false,
    keyCode: 16,
  },
  //   {
  //     key: 'Ctrl',
  //     code: 'ControlLeft',
  //     altKey: false,
  //     shiftKey: false,
  //     keyCode: 17,
  //   },
  {
    key: 'Ctrl',
    code: 'ControlLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 17,
  },
  {
    key: 'Alt',
    code: 'AltLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 17,
  },
  {
    key: 'Cmd',
    code: 'MetaLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 93,
  },
  {
    key: '_',
    code: 'Space',
    altKey: false,
    shiftKey: false,
    keyCode: 32,
  },
  {
    key: 'Cmd',
    code: 'MetaRight',
    altKey: false,
    shiftKey: false,
    keyCode: 93,
  },
  {
    key: 'Alt',
    code: 'AltRight',
    altKey: true,
    shiftKey: false,
    keyCode: 18,
  },
  {
    key: '←',
    code: 'ArrowLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 37,
  },
  {
    key: '↓',
    code: 'ArrowDown',
    altKey: false,
    shiftKey: false,
    keyCode: 40,
  },
  {
    key: '→',
    code: 'ArrowRight',
    altKey: false,
    shiftKey: false,
    keyCode: 39,
  },
  {
    key: '±',
    code: 'Backquote',
    altKey: false,
    shiftKey: true,
    keyCode: 192,
  },
  {
    key: '!',
    code: 'Digit1',
    altKey: false,
    shiftKey: true,
    keyCode: 49,
  },
  {
    key: '@',
    code: 'Digit2',
    altKey: false,
    shiftKey: true,
    keyCode: 50,
  },
  {
    key: '#',
    code: 'Digit3',
    altKey: false,
    shiftKey: true,
    keyCode: 51,
  },
  {
    key: '$',
    code: 'Digit4',
    altKey: false,
    shiftKey: true,
    keyCode: 52,
  },
  {
    key: '%',
    code: 'Digit5',
    altKey: false,
    shiftKey: true,
    keyCode: 53,
  },
  {
    key: '^',
    code: 'Digit6',
    altKey: false,
    shiftKey: true,
    keyCode: 54,
  },
  {
    key: '&',
    code: 'Digit7',
    altKey: false,
    shiftKey: true,
    keyCode: 55,
  },
  {
    key: '*',
    code: 'Digit8',
    altKey: false,
    shiftKey: true,
    keyCode: 56,
  },
  {
    key: '(',
    code: 'Digit9',
    altKey: false,
    shiftKey: true,
    keyCode: 57,
  },
  {
    key: ')',
    code: 'Digit0',
    altKey: false,
    shiftKey: true,
    keyCode: 48,
  },
  {
    key: '_',
    code: 'Minus',
    altKey: false,
    shiftKey: true,
    keyCode: 189,
  },
  {
    key: 'Q',
    code: 'KeyQ',
    altKey: false,
    shiftKey: true,
    keyCode: 81,
  },
  {
    key: 'W',
    code: 'KeyW',
    altKey: false,
    shiftKey: true,
    keyCode: 87,
  },
  {
    key: 'E',
    code: 'KeyE',
    altKey: false,
    shiftKey: true,
    keyCode: 69,
  },
  {
    key: 'R',
    code: 'KeyR',
    altKey: false,
    shiftKey: true,
    keyCode: 82,
  },
  {
    key: 'T',
    code: 'KeyT',
    altKey: false,
    shiftKey: true,
    keyCode: 84,
  },
  {
    key: 'Y',
    code: 'KeyY',
    altKey: false,
    shiftKey: true,
    keyCode: 89,
  },
  {
    key: 'U',
    code: 'KeyU',
    altKey: false,
    shiftKey: true,
    keyCode: 85,
  },
  {
    key: 'I',
    code: 'KeyI',
    altKey: false,
    shiftKey: true,
    keyCode: 73,
  },
  {
    key: 'O',
    code: 'KeyO',
    altKey: false,
    shiftKey: true,
    keyCode: 79,
  },
  {
    key: 'P',
    code: 'KeyP',
    altKey: false,
    shiftKey: true,
    keyCode: 80,
  },
  {
    key: '{',
    code: 'BracketLeft',
    altKey: false,
    shiftKey: true,
    keyCode: 219,
  },
  {
    key: '}',
    code: 'BracketRight',
    altKey: false,
    shiftKey: true,
    keyCode: 221,
  },
  {
    key: 'A',
    code: 'KeyA',
    altKey: false,
    shiftKey: true,
    keyCode: 65,
  },
  {
    key: 'S',
    code: 'KeyS',
    altKey: false,
    shiftKey: true,
    keyCode: 83,
  },
  {
    key: 'D',
    code: 'KeyD',
    altKey: false,
    shiftKey: true,
    keyCode: 68,
  },
  {
    key: 'F',
    code: 'KeyF',
    altKey: false,
    shiftKey: true,
    keyCode: 70,
  },
  {
    key: 'G',
    code: 'KeyG',
    altKey: false,
    shiftKey: true,
    keyCode: 71,
  },
  {
    key: 'H',
    code: 'KeyH',
    altKey: false,
    shiftKey: true,
    keyCode: 72,
  },
  {
    key: 'J',
    code: 'KeyJ',
    altKey: false,
    shiftKey: true,
    keyCode: 74,
  },
  {
    key: 'K',
    code: 'KeyK',
    altKey: false,
    shiftKey: true,
    keyCode: 75,
  },
  {
    key: 'L',
    code: 'KeyL',
    altKey: false,
    shiftKey: true,
    keyCode: 76,
  },
  {
    key: ':',
    code: 'Semicolon',
    altKey: false,
    shiftKey: true,
    keyCode: 186,
  },
  {
    key: '"',
    code: 'Quote',
    altKey: false,
    shiftKey: true,
    keyCode: 222,
  },
  {
    key: '|',
    code: 'Backslash',
    altKey: false,
    shiftKey: true,
    keyCode: 220,
  },
  {
    key: '~',
    code: 'IntlBackslash',
    altKey: false,
    shiftKey: true,
    keyCode: 192,
  },
  {
    key: 'Z',
    code: 'KeyZ',
    altKey: false,
    shiftKey: true,
    keyCode: 90,
  },
  {
    key: 'X',
    code: 'KeyX',
    altKey: false,
    shiftKey: true,
    keyCode: 88,
  },
  {
    key: 'C',
    code: 'KeyC',
    altKey: false,
    shiftKey: true,
    keyCode: 67,
  },
  {
    key: 'V',
    code: 'KeyV',
    altKey: false,
    shiftKey: true,
    keyCode: 86,
  },
  {
    key: 'B',
    code: 'KeyB',
    altKey: false,
    shiftKey: true,
    keyCode: 66,
  },
  {
    key: 'N',
    code: 'KeyN',
    altKey: false,
    shiftKey: true,
    keyCode: 78,
  },
  {
    key: 'M',
    code: 'KeyM',
    altKey: false,
    shiftKey: true,
    keyCode: 77,
  },
  {
    key: '<',
    code: 'Comma',
    altKey: false,
    shiftKey: true,
    keyCode: 188,
  },
  {
    key: '>',
    code: 'Period',
    altKey: false,
    shiftKey: true,
    keyCode: 190,
  },
  {
    key: '?',
    code: 'Slash',
    altKey: false,
    shiftKey: true,
    keyCode: 191,
  },
];

const shift = keysSet.filter((e) => !e.shiftKey);
const noShift = keysSet.filter((e) => e.shiftKey);

const en = shift.map((e) => {
  let noshiftkey = noShift.filter((s) => s.code === e.code)[0]?.key;
  if (!noshiftkey) {
    noshiftkey = e.key;
  }
  e.keyShift = noshiftkey;
  return e;
});

export default en;
