const keysSet = [
  {
    key: '>',
    code: 'Backquote',
    altKey: false,
    shiftKey: false,
    keyCode: 192,
  },
  {
    key: '1',
    code: 'Digit1',
    altKey: false,
    shiftKey: false,
    keyCode: 49,
  },
  {
    key: '2',
    code: 'Digit2',
    altKey: false,
    shiftKey: false,
    keyCode: 50,
  },
  {
    key: '3',
    code: 'Digit3',
    altKey: false,
    shiftKey: false,
    keyCode: 51,
  },
  {
    key: '4',
    code: 'Digit4',
    altKey: false,
    shiftKey: false,
    keyCode: 52,
  },
  {
    key: '5',
    code: 'Digit5',
    altKey: false,
    shiftKey: false,
    keyCode: 53,
  },
  {
    key: '6',
    code: 'Digit6',
    altKey: false,
    shiftKey: false,
    keyCode: 54,
  },
  {
    key: '7',
    code: 'Digit7',
    altKey: false,
    shiftKey: false,
    keyCode: 55,
  },
  {
    key: '8',
    code: 'Digit8',
    altKey: false,
    shiftKey: false,
    keyCode: 56,
  },
  {
    key: '9',
    code: 'Digit9',
    altKey: false,
    shiftKey: false,
    keyCode: 57,
  },
  {
    key: '0',
    code: 'Digit0',
    altKey: false,
    shiftKey: false,
    keyCode: 48,
  },
  {
    key: '-',
    code: 'Minus',
    altKey: false,
    shiftKey: false,
    keyCode: 189,
  },
  {
    key: '=',
    code: 'Equal',
    altKey: false,
    shiftKey: false,
    keyCode: 187,
  },
  {
    key: 'Backspace',
    code: 'Backspace',
    altKey: false,
    shiftKey: false,
    keyCode: 8,
  },
  {
    key: 'Tab',
    code: 'Tab',
    altKey: false,
    shiftKey: false,
    keyCode: 9,
  },
  {
    key: 'й',
    code: 'KeyQ',
    altKey: false,
    shiftKey: false,
    keyCode: 81,
  },
  {
    key: 'ц',
    code: 'KeyW',
    altKey: false,
    shiftKey: false,
    keyCode: 87,
  },
  {
    key: 'у',
    code: 'KeyE',
    altKey: false,
    shiftKey: false,
    keyCode: 69,
  },
  {
    key: 'к',
    code: 'KeyR',
    altKey: false,
    shiftKey: false,
    keyCode: 82,
  },
  {
    key: 'е',
    code: 'KeyT',
    altKey: false,
    shiftKey: false,
    keyCode: 84,
  },
  {
    key: 'н',
    code: 'KeyY',
    altKey: false,
    shiftKey: false,
    keyCode: 89,
  },
  {
    key: 'г',
    code: 'KeyU',
    altKey: false,
    shiftKey: false,
    keyCode: 85,
  },
  {
    key: 'ш',
    code: 'KeyI',
    altKey: false,
    shiftKey: false,
    keyCode: 73,
  },
  {
    key: 'щ',
    code: 'KeyO',
    altKey: false,
    shiftKey: false,
    keyCode: 79,
  },
  {
    key: 'з',
    code: 'KeyP',
    altKey: false,
    shiftKey: false,
    keyCode: 80,
  },
  {
    key: 'х',
    code: 'BracketLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 219,
  },
  {
    key: 'ъ',
    code: 'BracketRight',
    altKey: false,
    shiftKey: false,
    keyCode: 221,
  },
  {
    key: 'Enter',
    code: 'Enter',
    altKey: false,
    shiftKey: false,
    keyCode: 13,
  },
  {
    key: 'CapsLock',
    code: 'CapsLock',
    altKey: false,
    shiftKey: false,
    keyCode: 20,
  },
  {
    key: 'ф',
    code: 'KeyA',
    altKey: false,
    shiftKey: false,
    keyCode: 65,
  },
  {
    key: 'ы',
    code: 'KeyS',
    altKey: false,
    shiftKey: false,
    keyCode: 83,
  },
  {
    key: 'в',
    code: 'KeyD',
    altKey: false,
    shiftKey: false,
    keyCode: 68,
  },
  {
    key: 'а',
    code: 'KeyF',
    altKey: false,
    shiftKey: false,
    keyCode: 70,
  },
  {
    key: 'п',
    code: 'KeyG',
    altKey: false,
    shiftKey: false,
    keyCode: 71,
  },
  {
    key: 'р',
    code: 'KeyH',
    altKey: false,
    shiftKey: false,
    keyCode: 72,
  },
  {
    key: 'о',
    code: 'KeyJ',
    altKey: false,
    shiftKey: false,
    keyCode: 74,
  },
  {
    key: 'л',
    code: 'KeyK',
    altKey: false,
    shiftKey: false,
    keyCode: 75,
  },
  {
    key: 'д',
    code: 'KeyL',
    altKey: false,
    shiftKey: false,
    keyCode: 76,
  },
  {
    key: 'ж',
    code: 'Semicolon',
    altKey: false,
    shiftKey: false,
    keyCode: 186,
  },
  {
    key: 'э',
    code: 'Quote',
    altKey: false,
    shiftKey: false,
    keyCode: 222,
  },
  {
    key: 'ё',
    code: 'Backslash',
    altKey: false,
    shiftKey: false,
    keyCode: 220,
  },
  {
    key: 'Shift',
    code: 'ShiftLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 16,
  },
  {
    key: ']',
    code: 'IntlBackslash',
    altKey: false,
    shiftKey: false,
    keyCode: 192,
  },
  {
    key: 'я',
    code: 'KeyZ',
    altKey: false,
    shiftKey: false,
    keyCode: 90,
  },
  {
    key: 'ч',
    code: 'KeyX',
    altKey: false,
    shiftKey: false,
    keyCode: 88,
  },
  {
    key: 'с',
    code: 'KeyC',
    altKey: false,
    shiftKey: false,
    keyCode: 67,
  },
  {
    key: 'м',
    code: 'KeyV',
    altKey: false,
    shiftKey: false,
    keyCode: 86,
  },
  {
    key: 'и',
    code: 'KeyB',
    altKey: false,
    shiftKey: false,
    keyCode: 66,
  },
  {
    key: 'т',
    code: 'KeyN',
    altKey: false,
    shiftKey: false,
    keyCode: 78,
  },
  {
    key: 'ь',
    code: 'KeyM',
    altKey: false,
    shiftKey: false,
    keyCode: 77,
  },
  {
    key: 'б',
    code: 'Comma',
    altKey: false,
    shiftKey: false,
    keyCode: 188,
  },
  {
    key: 'ю',
    code: 'Period',
    altKey: false,
    shiftKey: false,
    keyCode: 190,
  },
  {
    key: '↑',
    code: 'ArrowUp',
    altKey: false,
    shiftKey: false,
    keyCode: 38,
  },
  {
    key: '/',
    code: 'Slash',
    altKey: false,
    shiftKey: false,
    keyCode: 191,
  },
  {
    key: 'Shift',
    code: 'ShiftRight',
    altKey: false,
    shiftKey: false,
    keyCode: 16,
  },
  //   {
  //     key: 'Ctrl',
  //     code: 'ControlLeft',
  //     altKey: false,
  //     shiftKey: false,
  //     keyCode: 17,
  //   },
  {
    key: 'Ctrl',
    code: 'ControlLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 17,
  },
  {
    key: 'Alt',
    code: 'AltLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 17,
  },
  {
    key: 'Cmd',
    code: 'MetaLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 93,
  },
  {
    key: '_',
    code: 'Space',
    altKey: false,
    shiftKey: false,
    keyCode: 32,
  },
  {
    key: 'Cmd',
    code: 'MetaRight',
    altKey: false,
    shiftKey: false,
    keyCode: 93,
  },
  {
    key: 'Alt',
    code: 'AltRight',
    altKey: true,
    shiftKey: false,
    keyCode: 18,
  },
  {
    key: '←',
    code: 'ArrowLeft',
    altKey: false,
    shiftKey: false,
    keyCode: 37,
  },
  {
    key: '↓',
    code: 'ArrowDown',
    altKey: false,
    shiftKey: false,
    keyCode: 40,
  },
  {
    key: '→',
    code: 'ArrowRight',
    altKey: false,
    shiftKey: false,
    keyCode: 39,
  },
  {
    key: '<',
    code: 'Backquote',
    altKey: false,
    shiftKey: true,
    keyCode: 192,
  },
  {
    key: '!',
    code: 'Digit1',
    altKey: false,
    shiftKey: true,
    keyCode: 49,
  },
  {
    key: '"',
    code: 'Digit2',
    altKey: false,
    shiftKey: true,
    keyCode: 50,
  },
  {
    key: '№',
    code: 'Digit3',
    altKey: false,
    shiftKey: true,
    keyCode: 51,
  },
  {
    key: '%',
    code: 'Digit4',
    altKey: false,
    shiftKey: true,
    keyCode: 52,
  },
  {
    key: ':',
    code: 'Digit5',
    altKey: false,
    shiftKey: true,
    keyCode: 53,
  },
  {
    key: ',',
    code: 'Digit6',
    altKey: false,
    shiftKey: true,
    keyCode: 54,
  },
  {
    key: '.',
    code: 'Digit7',
    altKey: false,
    shiftKey: true,
    keyCode: 55,
  },
  {
    key: ';',
    code: 'Digit8',
    altKey: false,
    shiftKey: true,
    keyCode: 56,
  },
  {
    key: '(',
    code: 'Digit9',
    altKey: false,
    shiftKey: true,
    keyCode: 57,
  },
  {
    key: ')',
    code: 'Digit0',
    altKey: false,
    shiftKey: true,
    keyCode: 48,
  },
  {
    key: '_',
    code: 'Minus',
    altKey: false,
    shiftKey: true,
    keyCode: 189,
  },
  {
    key: 'Й',
    code: 'KeyQ',
    altKey: false,
    shiftKey: true,
    keyCode: 81,
  },
  {
    key: 'Ц',
    code: 'KeyW',
    altKey: false,
    shiftKey: true,
    keyCode: 87,
  },
  {
    key: 'У',
    code: 'KeyE',
    altKey: false,
    shiftKey: true,
    keyCode: 69,
  },
  {
    key: 'К',
    code: 'KeyR',
    altKey: false,
    shiftKey: true,
    keyCode: 82,
  },
  {
    key: 'Е',
    code: 'KeyT',
    altKey: false,
    shiftKey: true,
    keyCode: 84,
  },
  {
    key: 'Н',
    code: 'KeyY',
    altKey: false,
    shiftKey: true,
    keyCode: 89,
  },
  {
    key: 'Г',
    code: 'KeyU',
    altKey: false,
    shiftKey: true,
    keyCode: 85,
  },
  {
    key: 'Ш',
    code: 'KeyI',
    altKey: false,
    shiftKey: true,
    keyCode: 73,
  },
  {
    key: 'Щ',
    code: 'KeyO',
    altKey: false,
    shiftKey: true,
    keyCode: 79,
  },
  {
    key: 'З',
    code: 'KeyP',
    altKey: false,
    shiftKey: true,
    keyCode: 80,
  },
  {
    key: 'Х',
    code: 'BracketLeft',
    altKey: false,
    shiftKey: true,
    keyCode: 219,
  },
  {
    key: 'Ъ',
    code: 'BracketRight',
    altKey: false,
    shiftKey: true,
    keyCode: 221,
  },
  {
    key: 'Ф',
    code: 'KeyA',
    altKey: false,
    shiftKey: true,
    keyCode: 65,
  },
  {
    key: 'Ы',
    code: 'KeyS',
    altKey: false,
    shiftKey: true,
    keyCode: 83,
  },
  {
    key: 'В',
    code: 'KeyD',
    altKey: false,
    shiftKey: true,
    keyCode: 68,
  },
  {
    key: 'А',
    code: 'KeyF',
    altKey: false,
    shiftKey: true,
    keyCode: 70,
  },
  {
    key: 'П',
    code: 'KeyG',
    altKey: false,
    shiftKey: true,
    keyCode: 71,
  },
  {
    key: 'Р',
    code: 'KeyH',
    altKey: false,
    shiftKey: true,
    keyCode: 72,
  },
  {
    key: 'О',
    code: 'KeyJ',
    altKey: false,
    shiftKey: true,
    keyCode: 74,
  },
  {
    key: 'Л',
    code: 'KeyK',
    altKey: false,
    shiftKey: true,
    keyCode: 75,
  },
  {
    key: 'Д',
    code: 'KeyL',
    altKey: false,
    shiftKey: true,
    keyCode: 76,
  },
  {
    key: 'Ж',
    code: 'Semicolon',
    altKey: false,
    shiftKey: true,
    keyCode: 186,
  },
  {
    key: 'Э',
    code: 'Quote',
    altKey: false,
    shiftKey: true,
    keyCode: 222,
  },
  {
    key: 'Ё',
    code: 'Backslash',
    altKey: false,
    shiftKey: true,
    keyCode: 220,
  },
  {
    key: '[',
    code: 'IntlBackslash',
    altKey: false,
    shiftKey: true,
    keyCode: 192,
  },
  {
    key: 'Я',
    code: 'KeyZ',
    altKey: false,
    shiftKey: true,
    keyCode: 90,
  },
  {
    key: 'Ч',
    code: 'KeyX',
    altKey: false,
    shiftKey: true,
    keyCode: 88,
  },
  {
    key: 'С',
    code: 'KeyC',
    altKey: false,
    shiftKey: true,
    keyCode: 67,
  },
  {
    key: 'М',
    code: 'KeyV',
    altKey: false,
    shiftKey: true,
    keyCode: 86,
  },
  {
    key: 'И',
    code: 'KeyB',
    altKey: false,
    shiftKey: true,
    keyCode: 66,
  },
  {
    key: 'Т',
    code: 'KeyN',
    altKey: false,
    shiftKey: true,
    keyCode: 78,
  },
  {
    key: 'Б',
    code: 'KeyM',
    altKey: false,
    shiftKey: true,
    keyCode: 77,
  },
  {
    key: 'Ю',
    code: 'Comma',
    altKey: false,
    shiftKey: true,
    keyCode: 188,
  },
  {
    key: '?',
    code: 'Period',
    altKey: false,
    shiftKey: true,
    keyCode: 190,
  },
  {
    key: '?',
    code: 'Slash',
    altKey: false,
    shiftKey: true,
    keyCode: 191,
  },
];

const shift = keysSet.filter((e) => !e.shiftKey);
const noShift = keysSet.filter((e) => e.shiftKey);

const ru = shift.map((e) => {
  let noshiftkey = noShift.filter((s) => s.code === e.code)[0]?.key;
  if (!noshiftkey) {
    noshiftkey = e.key;
  }
  e.keyShift = noshiftkey;
  return e;
});

export default ru;
